
const data = [
    {
        key: "aa",
        id: 1,
        name: "Paris",
        info:"Paris is the capital city of France, renowned for its iconic landmarks such as the Eiffel Tower, Louvre Museum, and Notre-Dame Cathedral. Paris is celebrated for its rich history, art, fashion, and culinary excellence. It serves as a global center for culture, literature, and philosophy, attracting millions of visitors each year ",
        image: process.env.PUBLIC_URL + "/images/paris.jpg",
        price: "325,456",
    },
    {
        key: "bb",
        id: 2,
        name: "Rio",
        info:"Rio is a vibrant city in Brazil famous for its stunning natural landscapes, including the iconic Copacabana and Ipanema beaches, as well as the towering Christ the Redeemer statue atop Corcovado Mountain. Renowned for its lively Carnival celebrations, Rio captivates with its samba music, dance, and festive atmosphere ",
        image: process.env.PUBLIC_URL + "/images/rio.jpg",
        price: "250,254",
    },
    {
        key: "cc",
        id: 3,
        name: "Mumbai",
        info:"Bombay is a bustling metropolis on the west coast of India. As the financial, commercial, and entertainment capital of the country, Mumbai is a melting pot of diverse cultures and communities. It is renowned for its iconic landmarks such as the Gateway of India, Marine Drive, and the historic Chhatrapati Shivaji Terminus ",
        image: process.env.PUBLIC_URL + "/images/mumbai.jpg",
        price: "15,456",
    },
    {
        key: "dd",
        id: 4,
        name: "Bali",
        info:"Bali is a tropical paradise and Indonesian island known for its lush landscapes, vibrant culture, and stunning beaches. Renowned for its picturesque rice terraces, ancient temples, and vibrant arts scene, Bali attracts visitors seeking a blend of natural beauty and spiritual tranquility. The island offers a diverse range of experiences, from surfing on pristine beaches to exploring traditional Balinese villages ",
        image: process.env.PUBLIC_URL + "/images/bali.jpg",
        price: "25,456",
    },
    {
        key: "ee",
        id: 5,
        name: "Hong Kong",
        info:"Hong Kong is a dynamic and bustling Special Administrative Region of China known for its iconic skyline, vibrant street life, and a mix of Eastern and Western influences. This global financial hub features towering skyscrapers, including Victoria Peak, and a stunning harbor. Hong Kong is celebrated for its diverse culinary scene, from traditional dim sum to international cuisine ",
        image: process.env.PUBLIC_URL + "/images/hong kong.jpg",
        price: "425,006",
    },
    {
        key: "ff",
        id: 6,
        name: "Jaipur",
        info:"Jaipur, the capital city of the Indian state of Rajasthan, is a vibrant and historic destination known for its rich cultural heritage. Jaipur is famous for its stunning palaces, including the Hawa Mahal (Palace of Winds), City Palace, and Amber Fort. The city is a showcase of Rajput architecture and design, with intricate palatial structures, vibrant bazaars, and bustling streets ",
        image: process.env.PUBLIC_URL + "/images/jaipr.jpg",
        price: "16,000",
    },
    {
        key: "gg",
        id: 7,
        name: "Las Vegas",
        info:"Las Vegas is a vibrant city in the Nevada desert known for its iconic resorts, extravagant casinos, and lively entertainment. The famous Las Vegas Strip is lined with themed hotels, dazzling lights, and world-class shows. The city is a hub for gambling and gaming, with numerous casinos offering a wide array of entertainment options",
        image: process.env.PUBLIC_URL + "/images/paris.jpg",
        price: "147,456",
    },
    {
        key: "hh",
        id: 8,
        name: "Moscow",
        info:"Moscow, the capital city of Russia, is a metropolis steeped in history and culture. Known for its iconic landmarks such as the Kremlin and Red Square, Moscow showcases a blend of medieval and modern architecture. The colorful onion domes of St. Basil's Cathedral add to the city's distinctive skyline. Moscow is a cultural hub with world-class museums, including the State Tretyakov Gallery and the Pushkin State Museum of Fine Arts ",
        image: process.env.PUBLIC_URL + '/images/moscow.jpg',
        price: "195,120",
    },
    {
        key: "ii",
        id: 9,
        name: "Dubai",
        info:"Dubai is a dynamic city in the United Arab Emirates known for its futuristic skyline, luxurious lifestyle, and ambitious architectural projects. This global hub is characterized by iconic landmarks like the Burj Khalifa, the world's tallest building, and the Palm Jumeirah, an artificial archipelago. Dubai is a center for business, tourism, and shopping, with extravagant malls like the Dubai Mall and traditional markets like the Gold Souk ",
        image: process.env.PUBLIC_URL + "/images/dubai.jpg",
        price: "400,000",
    },
    {
        key: "jjy",
        id: 10,
        name: "Goa",
        info:"Goa is a picturesque coastal state in southwestern India known for its beautiful beaches, vibrant nightlife, and rich cultural heritage. Famous for its colonial Portuguese architecture, Goa boasts charming churches and historic forts, including the Basilica of Bom Jesus and Fort Aguada. The region is celebrated for its lively atmosphere, with beach parties, water sports, and a diverse culinary scene ",
        image: process.env.PUBLIC_URL + "/images/goa.jpg",
        price: "40,236",
    },
]

export default data;